easy_admin:
    site_name: '<img src="https://symfony.com/logos/symfony_white_01.png" />'
    disabled_actions: ['delete']
    design:
        brand_color: '#1ABC9C'
    entities:
        # List the entity class name you want to manage
        Path:
            class: App\Entity\Path
        Player:
            class: App\Entity\Player
            help: 'Global message displayed in all views'
            list:
                fields: ['id', 'name', 'description','race', { property: 'picture', type: 'image' }, 'size']
            show:
            search:
                help: null
        Scene:
            class: App\Entity\Scene
            list:
                fields: ['id', 'name', 'description',{ property: 'picture', type: 'image' }, 'sound','players']
        User:
            class: App\Entity\User